export const userInputs = [

  {id: "name",
    label: "Full name",
    type: "text",
    placeholder: "Enter your Full-Name",
  },
  { id: "username",
    label: "Username",
    type: "text",
    placeholder: "Enter USer Name",
},
  {id: "email",
  label: "Email",
  type: "mail",
  placeholder: "Enter Email Adress",
  },
  { id: "password",
    label: "Password",
    type: "password",
    placeholder: "Enter Password",
    generateButton: true,
  },
  {id: "userType",
  label: "User Type",
  type: "select",
  options: [
    { value: "student", label: "Student" },
    { value: "almuni", label: "Almuni" },
    { value: "faculty", label: "Faculty Representative" },
    { value: "comunicator", label: "Campus-Communicator" },
  ],
  placeholder: "Select user Type",
  },
  {id: "privilage",
    label: "Privilage",
    type: "select",
    options: [
      { value: "", label: "none" },
      { value: "Faculty Representative", label: "Faculty Representative" },
      { value: "Communicator", label: "Campus-Communicator" },
    ],
    placeholder: "Select user Type",
    },

  { id: "university",
    label: "University",
    type: "select",
    placeholder: "Select University",
    options: [
      { value: "adigrat_university", label: "Adigrat University" },
      { value: "addis_ababa_university", label: "Addis Ababa University" },
      { value: "aksum_university", label: "Aksum University" },
      { value: "ambo_university", label: "Ambo University" },
      { value: "arbaminch_university", label: "Arbaminch University" },
      { value: "arba_minch_university", label: "Arba Minch University" },
      { value: "assosa_university", label: "Assosa University" },
      { value: "bahir_dar_university", label: "Bahir Dar University" },
      { value: "bule_hora_university", label: "Bule Hora University" },
      { value: "debre_birhan_university", label: "Debre Birhan University" },
      { value: "debre_markos_university", label: "Debre Markos University" },
      { value: "debre_tabor_university", label: "Debre Tabor University" },
      { value: "dilla_university", label: "Dilla University" },
      { value: "dire_dawa_university", label: "Dire Dawa University" },
      { value: "gamo_gofa_university", label: "Gamo Gofa University" },
      { value: "gambella_university", label: "Gambella University" },
      { value: "gondar_university", label: "Gondar University" },
      { value: "haramaya_university", label: "Haramaya University" },
      { value: "hawassa_university", label: "Hawassa University" },
      { value: "jimma_university", label: "Jimma University" },
      { value: "jijiga_university", label: "Jijiga University" },
      { value: "madawalabu_university", label: "Madawalabu University" },
      { value: "mekelle_university", label: "Mekelle University" },
      { value: "mizan_tepi_university", label: "Mizan Tepi University" },
      { value: "raya_university", label: "Raya University" },
      { value: "samara_university", label: "Samara University" },
      { value: "semera_university", label: "Semera University" },
      { value: "somali_state_university", label: "Somali State University" },
      { value: "wachemo_university", label: "Wachemo University" },
      { value: "welkite_university", label: "Welkite University" },
      { value: "woldiya_university", label: "Woldiya University" },
      { value: "wolkite_university", label: "Wolkite University" },
      { value: "wollo_university", label: "Wollo University" },
      { value: "woliso_university", label: "Woliso University" },
      { value: "wolaita_sodo_university", label: "Wolaita Sodo University" },
      { value: "wollega_university", label: "Wollega University" }
    ]
  },
  { id: "department",
    label: "Department",
    type: "select",
    placeholder: "Select Department",
    options: [ 
      { value: "accounting", label: "Accounting" },
      { value: "agriculture", label: "Agriculture" },
      { value: "animal_science", label: "Animal Science" },
      { value: "anthropology", label: "Anthropology" },
      { value: "architecture", label: "Architecture" },
      { value: "biology", label: "Biology" },
      { value: "biotechnology", label: "Biotechnology" },
      { value: "business_administration", label: "Business Administration" },
      { value: "chemistry", label: "Chemistry" },
      { value: "civil_engineering", label: "Civil Engineering" },
      { value: "computer_science", label: "Computer Science" },
      { value: "economics", label: "Economics" },
      { value: "education", label: "Education" },
      { value: "electrical_engineering", label: "Electrical Engineering" },
      { value: "english", label: "English" },
      { value: "environmental_science", label: "Environmental Science" },
      { value: "fine_arts", label: "Fine Arts" },
      { value: "geography", label: "Geography" },
      { value: "geology", label: "Geology" },
      { value: "history", label: "History" },
      { value: "information_technology", label: "Information Technology" },
      { value: "law", label: "Law" },
      { value: "linguistics", label: "Linguistics" },
      { value: "management", label: "Management" },
      { value: "marketing", label: "Marketing" },
      { value: "mathematics", label: "Mathematics" },
      { value: "mechanical_engineering", label: "Mechanical Engineering" },
      { value: "medicine", label: "Medicine" },
      { value: "nursing", label: "Nursing" },
      { value: "pharmacy", label: "Pharmacy" },
      { value: "physics", label: "Physics" },
      { value: "political_science", label: "Political Science" },
      { value: "public_administration", label: "Public Administration" },
      { value: "public_health", label: "Public Health" },
      { value: "social_work", label: "Social Work" },
      { value: "sociology", label: "Sociology" },
      { value: "statistics", label: "Statistics" },
      { value: "theology", label: "Theology" },
      { value: "veterinary_medicine", label: "Veterinary Medicine" }
    ]
  },
];


export const contentInputs = [
  {id: "title",
    label: "Title",
    type: "text",
    placeholder: "Enter Title",
  },
  {id: "description",
    label: "Description",
    type: "text",
    placeholder: "Enter Description",
  },
  {id: "author",
    label: "Author",
    type: "text",
    placeholder: "Enter Author's name",
  },
  {id: "createdDate",
    label: "Created Date",
    type: "date",
    placeholder: "Select a date",
  },
  { id: "contentType",
  label: "Content Type",
  type: "select",
  options: [
    { value: "post", label: "Post" },
    { value: "news", label: "News" },
    { value: "announcment", label: "Announcment" },
  ],
  placeholder: "Select content Type",
 },
  {id: "university",
    label: "University",
    type: "select",
    placeholder: "Select University",
    options: [
      { value: "adigrat_university", label: "Adigrat University" },
      { value: "addis_ababa_university", label: "Addis Ababa University" },
      { value: "aksum_university", label: "Aksum University" },
      { value: "ambo_university", label: "Ambo University" },
      { value: "arbaminch_university", label: "Arbaminch University" },
      { value: "arba_minch_university", label: "Arba Minch University" },
      { value: "assosa_university", label: "Assosa University" },
      { value: "bahir_dar_university", label: "Bahir Dar University" },
      { value: "bule_hora_university", label: "Bule Hora University" },
      { value: "debre_birhan_university", label: "Debre Birhan University" },
      { value: "debre_markos_university", label: "Debre Markos University" },
      { value: "debre_tabor_university", label: "Debre Tabor University" },
      { value: "dilla_university", label: "Dilla University" },
      { value: "dire_dawa_university", label: "Dire Dawa University" },
      { value: "gamo_gofa_university", label: "Gamo Gofa University" },
      { value: "gambella_university", label: "Gambella University" },
      { value: "gondar_university", label: "Gondar University" },
      { value: "haramaya_university", label: "Haramaya University" },
      { value: "hawassa_university", label: "Hawassa University" },
      { value: "jimma_university", label: "Jimma University" },
      { value: "jijiga_university", label: "Jijiga University" },
      { value: "madawalabu_university", label: "Madawalabu University" },
      { value: "mekelle_university", label: "Mekelle University" },
      { value: "mizan_tepi_university", label: "Mizan Tepi University" },
      { value: "raya_university", label: "Raya University" },
      { value: "samara_university", label: "Samara University" },
      { value: "semera_university", label: "Semera University" },
      { value: "somali_state_university", label: "Somali State University" },
      { value: "wachemo_university", label: "Wachemo University" },
      { value: "welkite_university", label: "Welkite University" },
      { value: "woldiya_university", label: "Woldiya University" },
      { value: "wolkite_university", label: "Wolkite University" },
      { value: "wollo_university", label: "Wollo University" },
      { value: "woliso_university", label: "Woliso University" },
      { value: "wolaita_sodo_university", label: "Wolaita Sodo University" },
      { value: "wollega_university", label: "Wollega University" }
    ]
  },
  {id: "department",
    label: "Department",
    type: "select",
    placeholder: "Select Department",
    options: [ 
      { value: "accounting", label: "Accounting" },
      { value: "agriculture", label: "Agriculture" },
      { value: "animal_science", label: "Animal Science" },
      { value: "anthropology", label: "Anthropology" },
      { value: "architecture", label: "Architecture" },
      { value: "biology", label: "Biology" },
      { value: "biotechnology", label: "Biotechnology" },
      { value: "business_administration", label: "Business Administration" },
      { value: "chemistry", label: "Chemistry" },
      { value: "civil_engineering", label: "Civil Engineering" },
      { value: "computer_science", label: "Computer Science" },
      { value: "economics", label: "Economics" },
      { value: "education", label: "Education" },
      { value: "electrical_engineering", label: "Electrical Engineering" },
      { value: "english", label: "English" },
      { value: "environmental_science", label: "Environmental Science" },
      { value: "fine_arts", label: "Fine Arts" },
      { value: "geography", label: "Geography" },
      { value: "geology", label: "Geology" },
      { value: "history", label: "History" },
      { value: "information_technology", label: "Information Technology" },
      { value: "law", label: "Law" },
      { value: "linguistics", label: "Linguistics" },
      { value: "management", label: "Management" },
      { value: "marketing", label: "Marketing" },
      { value: "mathematics", label: "Mathematics" },
      { value: "mechanical_engineering", label: "Mechanical Engineering" },
      { value: "medicine", label: "Medicine" },
      { value: "nursing", label: "Nursing" },
      { value: "pharmacy", label: "Pharmacy" },
      { value: "physics", label: "Physics" },
      { value: "political_science", label: "Political Science" },
      { value: "public_administration", label: "Public Administration" },
      { value: "public_health", label: "Public Health" },
      { value: "social_work", label: "Social Work" },
      { value: "sociology", label: "Sociology" },
      { value: "statistics", label: "Statistics" },
      { value: "theology", label: "Theology" },
      { value: "veterinary_medicine", label: "Veterinary Medicine" }
    ]
  },
 
  
 
];
